### ISSUE TITLE
Change over to consume new rights representation

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#472]
The latest ERMrest now includes a `"rights"` document in multiple levels of the model document. This describes the requesting client's permissions on the catalog so that clients do not need to interpret ACL content themselves.

Rights relevant to ermrestjs and Chaise:

1. Per-table rights
   - `"select"`: can query table
   - `"insert"`: can POST new rows to table
   - `"update"`: can mutate existing rows of table
   - `"delete"`: can delete existing rows of table
2. Per-column rights
   - `"select"`: can use column in queries
   - `"insert"`: can set data when creating new rows
   - `"update"`: can set data when modifying existing rows

Improvements to make in ermrestjs and chaise:

- [ ] Consider table *insert* permission to enable/disable the add/create button
- [ ] Consider table *update* permissions to enable/disable the row edit button
- [ ] Consider table *delete* permissions to enable/disable the row delete button
- [ ] Consider column permissions to validate and configure visible columns
   - Don't try to query columns w/o *select* permission
   - Exclude columns w/o *insert* permission in row creation mode
   - Exclude columns w/o *update* permission in row editing mode

Note, the model document can include tri-state values for rights:
- `true`: the permission is granted
- `false`: the permission is denied
- `null`: the decision is not known statically

In the above tasks, we should consider a `null` permission as "might possibly work" so we should enable the UX elements even though they might not work at runtime depending on the user and the specific records involved.  Data change requests might return success or forbidden when the rights are null.  Data query will return success if rights are null but might have some values filtered out.
