### ISSUE TITLE
Use the quantified value list enhancements of ERMrest

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/ermrestjs#958]
With the changes in [ermrest#246](https://github.com/informatics-isi-edu/ermrest/pull/246), we can now have quantified value lists in filter predicates in URL:

- `col1=any(X,Y,Z)` same as `col1=X;col1=Y;col1=Z`
- `col1=all(X,Y,Z)` same as `col1=X&col1=Y&col1=Z`

To make sure the specific ermrest installation on a server supports this feature, we would have to consult with the service announcement feature flag:

```json
{
  "version": "0.3.1",
  "features": {
    "trs": true,
    "tcrs": true,
    "history_control": true,
    "implicit_fkey_index": true,
    "catalog_post_input": true,
    "catalog_alias": true,
    "indexing_preferences": {
      "btree": true,
      "btree_column_list": true,
      "trgm": true,
      "gin_array": true
    },
    "quantified_value_lists": true,
    "quantified_rid_lists": true
  }
}
```
Notice the `quantified_value_lists` and `quantified_rid_lists ` in the `features`.

This syntactic sugar works consistently for all the binary predicates, whether or not a particular combination is very useful. You might express conjunctions or disjunctions which are pointless for a given column (type) or list of values. The following are the different places in ermrestjs/chaise that can use this syntax:

- [x] Faceting: `col1=any(...)` for the choices semantics of our current facet search controls (#963)
- [x] Search box: `*::ciregexp::all(...)` to require several patterns to match (#965). 
- [x] Column directive aggregate request: `col1=any(...)` for filtering based on the shortest key (useful only for simple keys) (#969).
- [x] Batch delete: same as above (#969).
- [x] Batch unlink: same as above (https://github.com/informatics-isi-edu/ermrestjs/commit/ef2f95aab1744212075cd611ad51ba5a53c87baf).
